### PR TITLE
Improve exobiology spawn predictions

### LINKED ISSUE #57: Large difference in number of predicted species with ED Observatory
The current implementation of exobiology predictions return a lot more species than elite observatory. Maybe this is caused by incorrect spawn conditions?

ED Observatory:
image

Journals:
image

### PR DESCRIPTION
**Pull request by Somfic**
This PR closes #57.

Results:

| Species | Test cases | False negatives | False positives |
| --- | --- | --- | --- |
| *Aleoida Arcus* | 35 | ✅ | 🚨 57.14% |
| *Aleoida Coronamus* | 56 | ✅ | 🚨 73.21% |
| *Aleoida Spica* | 17 | 🚨 100% | ✅ |
| *Aleoida Gravis* | 12 | ✅ | 🚨 83.33% |
| *Bacterium Aurasus* | 345 | ✅ | 🚨 12.17% |
| *Bacterium Scopulum* | 6 | ✅ | 🚨 83.33% |
| *Bacterium Acies* | 107 | ✅ | 🚨 12.15% |
| *Bacterium Vesicula* | 208 | ✅ | 🚨 7.69% |
| *Bacterium Alcyoneum* | 170 | ✅ | 🚨 16.47% |
| *Bacterium Tela* | 78 | 🚨 6.41% | 🚨 57.69% |
| *Bacterium Omentum* | 8 | ✅ | 🚨 75% |
| *Bacterium Cerbrus* | 229 | ✅ | 🚨 25.33% |
| *Bacterium Verrata* | 2 | ✅ | 🚨 50% |
| *Roseum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Gypseeum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Ostrinum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Viride Brain Tree* | 6 | ✅ | 🚨 100% |
| *Lividum Brain Tree * | 6 | ✅ | 🚨 100% |
| *Aureum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Puniceum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Lindigoticum Brain Tree* | 6 | ✅ | 🚨 100% |
| *Cactoida Cortexum* | 68 | ✅ | 🚨 100% |
| *Cactoida Lapis* | 148 | ✅ | 🚨 99.32% |
| *Cactoida Vermis* | 4 | ✅ | 🚨 75% |
| *Cactoida Pullulanta* | 68 | ✅ | 🚨 92.65% |
| *Cactoida Peperatis* | 148 | ✅ | 🚨 66.89% |
| *Clypeus Lacrimam* | 16 | ✅ | 🚨 68.75% |
| *Clypeus Margaritus* | 16 | ✅ | 🚨 62.5% |
| *Clypeus Speculumi* | 3 | 🚨 66.67% | 🚨 33.33% |
| *Concha Renibus* | 72 | ✅ | 🚨 70.83% |
| *Concha Aureolas* | 148 | ✅ | 🚨 92.57% |
| *Concha Labiata* | 257 | ✅ | 🚨 80.16% |
| *Concha Biconcavis* | 15 | ✅ | 🚨 100% |
| *Crystaline Shards* | 6 | 🚨 100% | ✅ |
| *Fonticulua Campestris* | 175 | ✅ | 🚨 34.29% |
| *Fonticulua Lapida* | 15 | ✅ | 🚨 26.67% |
| *Fonticulua Digitos* | 88 | ✅ | 🚨 61.36% |
| *Frutexa Flabellum* | 148 | ✅ | 🚨 97.97% |
| *Frutexa Acus* | 269 | ✅ | 🚨 96.65% |
| *Frutexa Metallicum* | 126 | ✅ | 🚨 61.9% |
| *Frutexa Flammasis* | 148 | ✅ | 🚨 70.27% |
| *Frutexa Fera* | 269 | ✅ | 🚨 100% |
| *Frutexa Sponsae* | 4 | ✅ | 🚨 100% |
| *Frutexa Collum* | 9 | ✅ | 🚨 100% |
| *Fumerola Carbosis* | 2 | 🚨 100% | ✅ |
| *Fumerola Nitris* | 2 | 🚨 100% | ✅ |
| *Fumerola Aquatis* | 1 | 🚨 100% | ✅ |
| *Fungoida Setisis* | 239 | ✅ | 🚨 50.21% |
| *Fungoida Stabitis* | 72 | ✅ | 🚨 98.61% |
| *Fungoida Bullarum* | 182 | ✅ | 🚨 91.76% |
| *Fungoida Gelata* | 72 | ✅ | 🚨 44.44% |
| *Osseus Fractus* | 68 | ✅ | 🚨 61.76% |
| *Osseus Discus* | 4 | ✅ | 🚨 50% |
| *Osseus Spiralis* | 148 | ✅ | 🚨 52.7% |
| *Osseus Pumice* | 281 | ✅ | 🚨 92.17% |
| *Osseus Cornibus* | 68 | ✅ | 🚨 97.06% |
| *Osseus Pellebantus* | 68 | ✅ | 🚨 95.59% |
| *Recepta Umbrux* | 9 | ✅ | 🚨 44.44% |
| *Recepta Deltahedronix* | 9 | ✅ | 🚨 88.89% |
| *Recepta Conditivus* | 8 | ✅ | 🚨 62.5% |
| *Albidum Sinuous Tubers* | 6 | ✅ | 🚨 100% |
| *Caeruleum Sinuous Tubers* | 6 | ✅ | 🚨 100% |
| *Lindigoticum Sinuous Tubers* | 6 | ✅ | 🚨 100% |
| *Stratum Excutitus* | 232 | ✅ | 🚨 100% |
| *Stratum Paleas* | 380 | ✅ | 🚨 82.11% |
| *Stratum Laminamus* | 106 | ✅ | 🚨 100% |
| *Stratum Araneamus* | 205 | ✅ | 🚨 97.07% |
| *Stratum Limaxus* | 232 | ✅ | 🚨 84.48% |
| *Stratum Cucumisis* | 243 | ✅ | 🚨 99.59% |
| *Stratum Tectonicas* | 363 | ✅ | 🚨 52.62% |
| *Stratum Frigus* | 243 | ✅ | 🚨 98.77% |
| *Tubus Conifer* | 138 | ✅ | 🚨 94.93% |
| *Tubus Sororibus* | 20 | ✅ | 🚨 60% |
| *Tubus Cavas* | 140 | ✅ | 🚨 50% |
| *Tubus Rosarium* | 29 | ✅ | 🚨 68.97% |
| *Tubus Compagibus* | 140 | ✅ | 🚨 97.86% |
| *Tussock Pennata* | 17 | ✅ | 🚨 94.12% |
| *Tussock Ventusa* | 27 | ✅ | 🚨 51.85% |
| *Tussock Ignis* | 71 | ✅ | 🚨 92.96% |
| *Tussock Cultro* | 148 | ✅ | 🚨 97.97% |
| *Tussock Catena* | 148 | ✅ | 🚨 23.65% |
| *Tussock Pennatis* | 269 | ✅ | 🚨 100% |
| *Tussock Serrati* | 51 | ✅ | 🚨 90.2% |
| *Tussock Albata* | 35 | ✅ | 🚨 88.57% |
| *Tussock Propagito* | 269 | ✅ | 🚨 25.28% |
| *Tussock Divisa* | 148 | ✅ | 🚨 93.92% |
| *Tussock Caputus* | 56 | ✅ | 🚨 89.29% |
| *Tussock Triticum* | 12 | ✅ | 🚨 91.67% |
| *Tussock Stigmasis* | 9 | ✅ | 🚨 88.89% |
| *Tussock Capillum* | 266 | ✅ | 🚨 95.86% |

### CODE REVIEW

**Comment by Somfic** [comment]
I'm finding that when working with the codebase in this repository the default cargo formatter modifies a lot of code, which makes staging small changes difficult. Are you following a specific style guide I can opt in to? I'd like to be on one line with how we format the code

**Comment by Somfic** [comment]
Closes #57.

**Comment by Somfic** [comment]
Results from implementing `is_landable` indicate that this check is not actually needed:

| | with check | without check |
| ---| ---| ---|
| false positives | 2620  | 2620 |

Doing some more research..

**Comment by Somfic** [comment]
Baseline of this PR:

| false positives | false negatives |
| --- | --- |
| 247.26% | 0.49% |

Not really sure yet what number we’re starving towards for the false positives, as even when all spawn conditions can match; a species is not guaranteed to spawn in-game.

**Comment by rster2002** [comment]
> I'm finding that when working with the codebase in this repository the default cargo formatter modifies a lot of code, which makes staging small changes difficult. Are you following a specific style guide I can opt in to? I'd like to be on one line with how we format the code

I usually just run `cargo fmt` and let it format it for me. I usually run it when finalizing things for a new release, so you don't really have to worry about it too much as long as PRs don't take multiple releases to merge.

**Comment by rster2002** [comment]
Looking through the https://github.com/Silarn/EDMC-BioScan rulesets, it also specifies region as a spawn condition. Looking at heatmaps here https://edastro.com/mapcharts/codex.html#codex it might also be something that could be tested. For example looking at this one:



It seems that Sinuous tubers spawn in specific regions or near nebula (at least that is what I guess are those spots in the other regions)

**Comment by Somfic** [comment]
That kinda sucks, as the region is only able to be extracted from a `CodexEntry` event, which only triggers *after* scanning a exobiological signal.

**Comment by rster2002** [comment]
@klightspeed has come to the rescue! https://github.com/klightspeed/EliteDangerousRegionMap even has Rust files!

**Comment by rster2002** [comment]
Can probably add this to the project in the `Region` enum, something like `Region::from_pos(pos: [f32; 3]) -> Region`

**Comment by rster2002** [comment]
@Somfic can I take this over or do you still want to work on this?

**Comment by Somfic** [comment]
Hi, sorry lately I have been busy with finishing up uni and other projects, so feel free to take over this PR. The biggest change was the introduction of a few macros to make defining spawn conditions a bit smoother. Was working on updating the spawn conditions for each species, the commit messages should indicate which ones I finished.

**Comment by rster2002** [comment]
No problem. IRL things go first after all. Thanks for the work you've already put in!

**Comment by rster2002** [comment]
Continued in #70

**Pull request closed without merging**
